Adiciona suporte a tags do tipo "richtext"
ricardolsmendes/datacatalog-tag-manager pull request #42
Opened 2022-05-30 15:37 UTC by adsamuelmorais

Adição do método e da entrada para recebimento de dados no formato Rich Text. O tipo richtext suporta um volume maior de caracteres na tag (10k)

2022-05-30 23:16 UTC, ricardolsmendes requested changes
@adsamuelmorais, obrigado por submeter essa PR. Deixei duas sugestões de melhoria no código. Precisamos também de adicionar cobertura de teste unitário para o método `__set_richtext_field_value` na classe [DataCatalogEntityFactoryTest](https://github.com/ricardolsmendes/datacatalog-tag-manager/blob/master/tests/datacatalog_tag_manager/datacatalog_entity_factory_test.py).

Você conseguiria resolver essas questões? Obrigado!

2022-05-30 23:16 UTC, ricardolsmendes commented on src/datacatalog_tag_manager/datacatalog_entity_factory.py
> +            datacatalog.FieldType.PrimitiveType.RICHTEXT: cls.__set_richtext_field_value
Sugestão: adicionar essa linha imediatamente antes de `datacatalog.FieldType.PrimitiveType.STRING: cls.__set_string_field_value,`, mantendo a ordem alfabética para assegurar melhor legibilidade do código.

2022-05-30 23:16 UTC, ricardolsmendes commented on src/datacatalog_tag_manager/datacatalog_entity_factory.py
> +    def __set_richtext_field_value(cls, field, value):
Sugestão: adicionar esse método antes da declaração de `__set_string_field_value`.

2022-06-06 19:43 UTC, samuelmorais87 approved these changes

2022-06-07 12:55 UTC, samuelmorais87 reviewed
Reorganiza métodos para melhor legibilidade do código

2022-06-07 12:59 UTC, samuelmorais87 commented on src/datacatalog_tag_manager/datacatalog_entity_factory.py
> +            datacatalog.FieldType.PrimitiveType.RICHTEXT: cls.__set_richtext_field_value
Ordem alterada

2022-06-07 13:00 UTC, samuelmorais87 commented on src/datacatalog_tag_manager/datacatalog_entity_factory.py
> +    def __set_richtext_field_value(cls, field, value):
Ordem alterada

2022-06-07 13:28 UTC, ricardolsmendes commented
@adsamuelmorais, obrigado por trabalhar nas melhorias. Vi que o CI falou e tem algumas questões de compatibilidade do `pytest` com Python 3.6. Vou corrigir isso numa branch à parte e logo mais te aviso para fazer o rebase, ok?

2022-06-07 17:28 UTC, ricardolsmendes commented
@adsamuelmorais, acabei de mergear a PR https://github.com/ricardolsmendes/datacatalog-tag-manager/pull/43, que define as versões corretas para as dependências relacionadas ao `pytest`. Você pode fazer o rebase dessa branch a partir da `master`, por favor? Obrigado!

2022-07-19 22:50 UTC, ricardolsmendes commented
> @adsamuelmorais, acabei de mergear a PR #43, que define as versões corretas para as dependências relacionadas ao `pytest`. Você pode fazer o rebase dessa branch a partir da `master`, por favor? Obrigado!

@adsamuelmorais, tudo bem? Posso te ajudar de alguma forma em relação a esse rebase para que possamos concluir essa PR?

2022-07-29 20:33 UTC, merged

2022-07-29 20:56 UTC, ricardolsmendes commented
@adsamuelmorais, obrigado pela sua contribuição. Eu fiz o merge da PR, mas o teste unitária ainda está quebrando. Vou ver se corrijo aqui, mas fique à vontade se quiser tentar o fix também. Só me avise para evitarmos retrabalho. 😄